# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Whatchamacallit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Whatchamacallit
  pod 'Firebase/Core'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
